{
  "Architecture": [
    "all"
  ],
  "Binary": [
    "python3-zope.exceptions"
  ],
  "Build-Depends": [
    "debhelper-compat (= 13), dh-sequence-python3, pybuild-plugin-pyproject, python3-all, python3-setuptools, python3-zope.interface, python3-zope.testrunner"
  ],
  "Checksums-Sha256": [
    "28b505e911ff374b5f626f42f6a76d36c9b2379d9ba6208389b4734fcd491ae2 2195 zope.exceptions_6.0-2.dsc 0ac0e078ecdd8acb5da231c39fc6454bdf3249216fd1c06d0578bf8ea6bf3299 32036 zope.exceptions_6.0.orig.tar.gz 054e35a6912a9729ec7e1abe5d4376683c10e0b3e29d76bb4fee20e53207247c 5372 zope.exceptions_6.0-2.debian.tar.xz"
  ],
  "Directory": [
    "pool/main/z/zope.exceptions"
  ],
  "Files": [
    "8e25ed6c2c0021d0811cde4614372687 2195 zope.exceptions_6.0-2.dsc 9d7384b16ab4f480a38acf5bc35c7e56 32036 zope.exceptions_6.0.orig.tar.gz 5fccad1b0d4b0dc422704d64109515dc 5372 zope.exceptions_6.0-2.debian.tar.xz"
  ],
  "Format": [
    "3.0 (quilt)"
  ],
  "Homepage": [
    "https://github.com/zopefoundation/zope.exceptions"
  ],
  "Maintainer": [
    "Debian Python Team \u003cteam+python@tracker.debian.org\u003e"
  ],
  "Package": [
    "zope.exceptions"
  ],
  "Package-List": [
    "python3-zope.exceptions deb zope optional arch=all"
  ],
  "Priority": [
    "source"
  ],
  "Section": [
    "python"
  ],
  "Standards-Version": [
    "4.7.2"
  ],
  "Testsuite": [
    "autopkgtest-pkg-pybuild"
  ],
  "Uploaders": [
    "Colin Watson \u003ccjwatson@debian.org\u003e,"
  ],
  "Vcs-Browser": [
    "https://salsa.debian.org/python-team/packages/zope.exceptions"
  ],
  "Vcs-Git": [
    "https://salsa.debian.org/python-team/packages/zope.exceptions.git"
  ],
  "Version": [
    "6.0-2"
  ]
}