{
  "Architecture": [
    "all"
  ],
  "Binary": [
    "python3-zope.exceptions"
  ],
  "Build-Depends": [
    "debhelper-compat (= 13), dh-sequence-python3, pybuild-plugin-pyproject, python3-all, python3-setuptools, python3-zope.interface, python3-zope.testrunner"
  ],
  "Checksums-Sha256": [
    "e3fb5640ac64eeeb20a015709eaa171fb42930ce50c2667355b1ffc684a98715 2288 zope.exceptions_6.0-1.dsc 0ac0e078ecdd8acb5da231c39fc6454bdf3249216fd1c06d0578bf8ea6bf3299 32036 zope.exceptions_6.0.orig.tar.gz aa15abc7b3d4557dc6393035c500b678a8c3059bf34380c70da949f4bb507ce8 4996 zope.exceptions_6.0-1.debian.tar.xz"
  ],
  "Dgit": [
    "dd72c6b6e23b7438a6e35a8ddd4b395f8f41026f debian archive/debian/6.0-1 https://git.dgit.debian.org/zope.exceptions"
  ],
  "Directory": [
    "pool/main/z/zope.exceptions"
  ],
  "Files": [
    "704150e22769f051bb68e343bfd98348 2288 zope.exceptions_6.0-1.dsc 9d7384b16ab4f480a38acf5bc35c7e56 32036 zope.exceptions_6.0.orig.tar.gz 4e68b98b3f8f00e77569b496325fcb87 4996 zope.exceptions_6.0-1.debian.tar.xz"
  ],
  "Format": [
    "3.0 (quilt)"
  ],
  "Homepage": [
    "https://github.com/zopefoundation/zope.exceptions"
  ],
  "Maintainer": [
    "Debian Python Team \u003cteam+python@tracker.debian.org\u003e"
  ],
  "Package": [
    "zope.exceptions"
  ],
  "Package-List": [
    "python3-zope.exceptions deb zope optional arch=all"
  ],
  "Priority": [
    "source"
  ],
  "Section": [
    "python"
  ],
  "Standards-Version": [
    "4.7.2"
  ],
  "Testsuite": [
    "autopkgtest-pkg-pybuild"
  ],
  "Uploaders": [
    "Colin Watson \u003ccjwatson@debian.org\u003e,"
  ],
  "Vcs-Browser": [
    "https://salsa.debian.org/python-team/packages/zope.exceptions"
  ],
  "Vcs-Git": [
    "https://salsa.debian.org/python-team/packages/zope.exceptions.git"
  ],
  "Version": [
    "6.0-1"
  ]
}