{
  "Header": {
    "Original": "CVE-2025-0938 (The Python standard library functions `urllib.parse.urlsplit` and `url ...)",
    "ID": "CVE-2025-0938",
    "Description": "(The Python standard library functions `urllib.parse.urlsplit` and `url ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-4087-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-4087-1"
      ]
    },
    {
      "Original": "- python3.13 3.13.2-1",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "fixed",
      "Version": "3.13.2-1"
    },
    {
      "Original": "- python3.12 3.12.9-1",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "fixed",
      "Version": "3.12.9-1"
    },
    {
      "Original": "- python3.11 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "removed"
    },
    {
      "Original": "[bookworm] - python3.11 3.11.2-6+deb12u6",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python3.11",
      "Kind": "fixed",
      "Version": "3.11.2-6+deb12u6"
    },
    {
      "Original": "- python3.9 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "removed"
    },
    {
      "Original": "- pypy3 7.3.18+dfsg-2",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.18+dfsg-2"
    },
    {
      "Original": "[bookworm] - pypy3 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pypy3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bullseye] - pypy3 \u003cpostponed\u003e (Minor issue)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "pypy3",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://mail.python.org/archives/list/security-announce@python.org/thread/K4EUG6EKV6JYFIC24BASYOZS4M5XOQIB/",
      "Type": "NOTE",
      "Description": "https://mail.python.org/archives/list/security-announce@python.org/thread/K4EUG6EKV6JYFIC24BASYOZS4M5XOQIB/"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/105704",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/105704"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/129418",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/129418"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/d89a5f6a6e65511a5f6e0618c4c30a7aa5aba56a",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/d89a5f6a6e65511a5f6e0618c4c30a7aa5aba56a"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/90e526ae67b172ed7c6c56e7edad36263b0f9403 (v3.13.2)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/90e526ae67b172ed7c6c56e7edad36263b0f9403 (v3.13.2)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/a7084f6075c9595ba60119ce8c62f1496f50c568 (v3.12.9)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/a7084f6075c9595ba60119ce8c62f1496f50c568 (v3.12.9)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/129528 (3.11)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/129528 (3.11)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/129530 (3.9)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/129530 (3.9)"
    }
  ]
}