{
  "Header": {
    "Original": "CVE-2025-46148 (In PyTorch through 2.6.0, when eager is used, nn.PairwiseDistance(p=2) ...)",
    "ID": "CVE-2025-46148",
    "Description": "(In PyTorch through 2.6.0, when eager is used, nn.PairwiseDistance(p=2) ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e (bug #1116543)",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed",
      "BugNo": 1116543
    },
    {
      "Original": "[trixie] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "trixie",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bookworm] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/151198",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/151198"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/pull/152993",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/pull/152993"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/pytorch/pytorch/commit/e5f869999cf5429e24fbb5c3923a5c795549b9e7 (v2.8.0-rc1)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/pytorch/pytorch/commit/e5f869999cf5429e24fbb5c3923a5c795549b9e7 (v2.8.0-rc1)"
    }
  ]
}