{
  "Header": {
    "Original": "CVE-2025-46801 (Pgpool-II provided by PgPool Global Development Group contains an auth ...)",
    "ID": "CVE-2025-46801",
    "Description": "(Pgpool-II provided by PgPool Global Development Group contains an auth ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5974-1 DLA-4334-1}",
      "Type": "xref",
      "Bugs": [
        "DSA-5974-1",
        "DLA-4334-1"
      ]
    },
    {
      "Original": "- pgpool2 4.6.1-1 (bug #1106119)",
      "Type": "package",
      "Package": "pgpool2",
      "Kind": "fixed",
      "Version": "4.6.1-1",
      "BugNo": 1106119
    },
    {
      "Original": "NOTE: https://www.pgpool.net/mediawiki/index.php/Main_Page#Pgpool-II_4.6.1.2C_4.5.7.2C_4.4.12.2C_4.3.15_and_4.2.22_officially_released_.282025.2F05.2F15.29_2",
      "Type": "NOTE",
      "Description": "https://www.pgpool.net/mediawiki/index.php/Main_Page#Pgpool-II_4.6.1.2C_4.5.7.2C_4.4.12.2C_4.3.15_and_4.2.22_officially_released_.282025.2F05.2F15.29_2"
    },
    {
      "Original": "NOTE: Fixed by: https://git.postgresql.org/gitweb/?p=pgpool2.git;a=commit;h=d8e2ace8737f64eee2bf5ca74f6294835fb75ccb (V4_6_1)",
      "Type": "NOTE",
      "Description": "Fixed by: https://git.postgresql.org/gitweb/?p=pgpool2.git;a=commit;h=d8e2ace8737f64eee2bf5ca74f6294835fb75ccb (V4_6_1)"
    }
  ]
}