{
  "Header": {
    "Original": "CVE-2025-61783 (Python Social Auth is a social authentication/registration mechanism.  ...)",
    "ID": "CVE-2025-61783",
    "Description": "(Python Social Auth is a social authentication/registration mechanism.  ...)"
  },
  "Annotations": [
    {
      "Original": "- social-auth-app-django \u003cunfixed\u003e",
      "Type": "package",
      "Package": "social-auth-app-django",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-wv4w-6qv2-qqfg",
      "Type": "NOTE",
      "Description": "https://github.com/python-social-auth/social-app-django/security/advisories/GHSA-wv4w-6qv2-qqfg"
    },
    {
      "Original": "NOTE: https://github.com/python-social-auth/social-app-django/issues/220",
      "Type": "NOTE",
      "Description": "https://github.com/python-social-auth/social-app-django/issues/220"
    },
    {
      "Original": "NOTE: https://github.com/python-social-auth/social-app-django/issues/231",
      "Type": "NOTE",
      "Description": "https://github.com/python-social-auth/social-app-django/issues/231"
    },
    {
      "Original": "NOTE: https://github.com/python-social-auth/social-app-django/issues/634",
      "Type": "NOTE",
      "Description": "https://github.com/python-social-auth/social-app-django/issues/634"
    },
    {
      "Original": "NOTE: https://github.com/python-social-auth/social-app-django/pull/803",
      "Type": "NOTE",
      "Description": "https://github.com/python-social-auth/social-app-django/pull/803"
    },
    {
      "Original": "NOTE: https://github.com/python-social-auth/social-app-django/commit/10c80e2ebabeccd4e9c84ad0e16e1db74148ed4c (5.6.0)",
      "Type": "NOTE",
      "Description": "https://github.com/python-social-auth/social-app-django/commit/10c80e2ebabeccd4e9c84ad0e16e1db74148ed4c (5.6.0)"
    }
  ]
}