{
  "Header": {
    "Original": "CVE-2025-46149 (In PyTorch before 2.7.0, when inductor is used, nn.Fold has an asserti ...)",
    "ID": "CVE-2025-46149",
    "Description": "(In PyTorch before 2.7.0, when inductor is used, nn.Fold has an asserti ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e (bug #1116541)",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed",
      "BugNo": 1116541
    },
    {
      "Original": "[trixie] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "trixie",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bookworm] - pytorch \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "pytorch",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/147848",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/147848"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/pull/147961",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/pull/147961"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/pytorch/pytorch/commit/be830c8b1c496277491bbbdd40a5cb35de17d5fb (v2.7.0-rc1)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/pytorch/pytorch/commit/be830c8b1c496277491bbbdd40a5cb35de17d5fb (v2.7.0-rc1)"
    }
  ]
}